apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federateddeployments.federation.k8s.io
spec:
  group: federation.k8s.io
  names:
    kind: FederatedDeployment
    listKind: FederatedDeploymentList
    plural: federateddeployments
    singular: federateddeployment
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            template:
              type: object
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: FederatedDeployment
    listKind: FederatedDeploymentList
    plural: federateddeployments
    singular: federateddeployment
  conditions: null
